# Reference for docker-compose
# https://levelup.gitconnected.com/dockerized-crud-restful-api-with-go-gorm-jwt-postgresql-mysql-and-testing-61d731430bd8

version: '3.9'
services:
  db:
    container_name: golang-url-shortener-postgres
    image: "postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/url_shortener/
    ports:
    # <Port exposed> : < Postgres Port running inside container>
      - '5433:5432'
    volumes: 
      - my-db:/var/lib/postgresql/data
    networks:
      - default

  app:
    container_name: golang_url_shortener
    tty: true
    build: .
    ports:
      - 5000:5000
    restart: on-failure
    volumes:
      -  api:/usr/src/app/
    depends_on:
      - db
    networks:
      - default
 
# Names our volume
volumes:
  api:
  my-db:

# Networks to be created to facilitate communication between containers
networks:
  default:
    driver: bridge