version: '3.9'
services:
  db:
    container_name: url_shortener_mysql_standalone
    restart: always
    image: mysql:5.7
    environment:
      # Mysql Database
      - MYSQL_DATABASE="${DATABASE_NAME}"
      # Mysql Password
      - MYSQL_ROOT_PASSWORD="${DATABASE_PASSWORD}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql_url_shortener
    networks:
      - default

# Names our volume
volumes:
  my-db:
    driver: local