// Code generated by MockGen. DO NOT EDIT.
// Source: src/business/domain/url/url.go
//
// Generated by this command:
//
//	mockgen -source src/business/domain/url/url.go -destination src/business/domain/mock/url/url.go
//

// Package mock_url is a generated GoMock package.
package mock_url

import (
	context "context"
	reflect "reflect"

	entity "github.com/adiatma85/golang-url-shortener/src/business/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInterface) Create(ctx context.Context, insertParam entity.CreateUrlParam) (entity.Url, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, insertParam)
	ret0, _ := ret[0].(entity.Url)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInterfaceMockRecorder) Create(ctx, insertParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInterface)(nil).Create), ctx, insertParam)
}

// Get mocks base method.
func (m *MockInterface) Get(ctx context.Context, params entity.UrlParam) (entity.Url, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, params)
	ret0, _ := ret[0].(entity.Url)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInterfaceMockRecorder) Get(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInterface)(nil).Get), ctx, params)
}

// GetList mocks base method.
func (m *MockInterface) GetList(ctx context.Context, params entity.UrlParam) ([]entity.Url, *entity.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, params)
	ret0, _ := ret[0].([]entity.Url)
	ret1, _ := ret[1].(*entity.Pagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockInterfaceMockRecorder) GetList(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockInterface)(nil).GetList), ctx, params)
}

// Update mocks base method.
func (m *MockInterface) Update(ctx context.Context, updateParam entity.UpdateUrlParam, selectParam entity.UrlParam) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, updateParam, selectParam)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockInterfaceMockRecorder) Update(ctx, updateParam, selectParam any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInterface)(nil).Update), ctx, updateParam, selectParam)
}
